name: Build e Analise de Qualidade SonarQube

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Necessário para que o SonarQube analise todo o histórico
          fetch-depth: 0 

      # Configurar o ambiente Java (versão 21 ou superior)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      # Análise SonarQube e Build Maven
      - name: Build and Analyze
        env:
          # Variáveis SONAR_TOKEN e GITHUB_TOKEN obtêm o valor do GitHub Secrets
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=GITHUB_ACTIONS_TOKEN
